//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.ISS5
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Вид поддержки.
    /// </summary>
    // *** Start programmer edit section *** (ВидПоддержки CustomAttributes)

    // *** End programmer edit section *** (ВидПоддержки CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ВидПоддержкиE", new string[] {
            "НомерУсловия as \'Номер условия\'",
            "Наименование as \'Наименование\'",
            "Пользователь as \'Пользователь\'",
            "Пользователь.ФИО as \'ФИО\'"}, Hidden=new string[] {
            "Пользователь.ФИО"})]
    [MasterViewDefineAttribute("ВидПоддержкиE", "Пользователь", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    public class ВидПоддержки : ICSSoft.STORMNET.DataObject
    {
        
        private string fНомерУсловия;
        
        private string fНаименование;
        
        private IIS.ISS5.Пользователь fПользователь;
        
        private IIS.ISS5.Условие fУсловие;
        
        // *** Start programmer edit section *** (ВидПоддержки CustomMembers)

        // *** End programmer edit section *** (ВидПоддержки CustomMembers)

        
        /// <summary>
        /// НомерУсловия.
        /// </summary>
        // *** Start programmer edit section *** (ВидПоддержки.НомерУсловия CustomAttributes)

        // *** End programmer edit section *** (ВидПоддержки.НомерУсловия CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string НомерУсловия
        {
            get
            {
                // *** Start programmer edit section *** (ВидПоддержки.НомерУсловия Get start)

                // *** End programmer edit section *** (ВидПоддержки.НомерУсловия Get start)
                string result = this.fНомерУсловия;
                // *** Start programmer edit section *** (ВидПоддержки.НомерУсловия Get end)

                // *** End programmer edit section *** (ВидПоддержки.НомерУсловия Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ВидПоддержки.НомерУсловия Set start)

                // *** End programmer edit section *** (ВидПоддержки.НомерУсловия Set start)
                this.fНомерУсловия = value;
                // *** Start programmer edit section *** (ВидПоддержки.НомерУсловия Set end)

                // *** End programmer edit section *** (ВидПоддержки.НомерУсловия Set end)
            }
        }
        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (ВидПоддержки.Наименование CustomAttributes)

        // *** End programmer edit section *** (ВидПоддержки.Наименование CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (ВидПоддержки.Наименование Get start)

                // *** End programmer edit section *** (ВидПоддержки.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (ВидПоддержки.Наименование Get end)

                // *** End programmer edit section *** (ВидПоддержки.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ВидПоддержки.Наименование Set start)

                // *** End programmer edit section *** (ВидПоддержки.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (ВидПоддержки.Наименование Set end)

                // *** End programmer edit section *** (ВидПоддержки.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Вид поддержки.
        /// </summary>
        // *** Start programmer edit section *** (ВидПоддержки.Пользователь CustomAttributes)

        // *** End programmer edit section *** (ВидПоддержки.Пользователь CustomAttributes)
        [NotNull()]
        public virtual IIS.ISS5.Пользователь Пользователь
        {
            get
            {
                // *** Start programmer edit section *** (ВидПоддержки.Пользователь Get start)

                // *** End programmer edit section *** (ВидПоддержки.Пользователь Get start)
                IIS.ISS5.Пользователь result = this.fПользователь;
                // *** Start programmer edit section *** (ВидПоддержки.Пользователь Get end)

                // *** End programmer edit section *** (ВидПоддержки.Пользователь Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ВидПоддержки.Пользователь Set start)

                // *** End programmer edit section *** (ВидПоддержки.Пользователь Set start)
                this.fПользователь = value;
                // *** Start programmer edit section *** (ВидПоддержки.Пользователь Set end)

                // *** End programmer edit section *** (ВидПоддержки.Пользователь Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.ISS5.Условие.
        /// </summary>
        // *** Start programmer edit section *** (ВидПоддержки.Условие CustomAttributes)

        // *** End programmer edit section *** (ВидПоддержки.Условие CustomAttributes)
        [Agregator()]
        [NotNull()]
        public virtual IIS.ISS5.Условие Условие
        {
            get
            {
                // *** Start programmer edit section *** (ВидПоддержки.Условие Get start)

                // *** End programmer edit section *** (ВидПоддержки.Условие Get start)
                IIS.ISS5.Условие result = this.fУсловие;
                // *** Start programmer edit section *** (ВидПоддержки.Условие Get end)

                // *** End programmer edit section *** (ВидПоддержки.Условие Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ВидПоддержки.Условие Set start)

                // *** End programmer edit section *** (ВидПоддержки.Условие Set start)
                this.fУсловие = value;
                // *** Start programmer edit section *** (ВидПоддержки.Условие Set end)

                // *** End programmer edit section *** (ВидПоддержки.Условие Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ВидПоддержкиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ВидПоддержкиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ВидПоддержкиE", typeof(IIS.ISS5.ВидПоддержки));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ВидПоддержки.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfВидПоддержки CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfВидПоддержки CustomAttributes)
    public class DetailArrayOfВидПоддержки : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.ISS5.DetailArrayOfВидПоддержки members)

        // *** End programmer edit section *** (IIS.ISS5.DetailArrayOfВидПоддержки members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ВидПоддержки by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ВидПоддержки.
        /// </summary>
        public DetailArrayOfВидПоддержки(IIS.ISS5.Условие fУсловие) : 
                base(typeof(ВидПоддержки), ((ICSSoft.STORMNET.DataObject)(fУсловие)))
        {
        }
        
        public IIS.ISS5.ВидПоддержки this[int index]
        {
            get
            {
                return ((IIS.ISS5.ВидПоддержки)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.ISS5.ВидПоддержки dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
