//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.ISS5
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Условие.
    /// </summary>
    // *** Start programmer edit section *** (Условие CustomAttributes)

    // *** End programmer edit section *** (Условие CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("УсловиеE", new string[] {
            "НомерУсловия as \'Номер условия\'",
            "Наименование as \'Наименование\'"})]
    [AssociatedDetailViewAttribute("УсловиеE", "ВидПоддержки", "ВидПоддержкиE", true, "", "Вид поддержки", true, new string[] {
            ""})]
    [View("УсловиеL", new string[] {
            "НомерУсловия as \'Номер условия\'",
            "Наименование as \'Наименование\'"})]
    public class Условие : ICSSoft.STORMNET.DataObject
    {
        
        private string fНомерУсловия;
        
        private string fНаименование;
        
        private IIS.ISS5.DetailArrayOfВидПоддержки fВидПоддержки;
        
        // *** Start programmer edit section *** (Условие CustomMembers)

        // *** End programmer edit section *** (Условие CustomMembers)

        
        /// <summary>
        /// НомерУсловия.
        /// </summary>
        // *** Start programmer edit section *** (Условие.НомерУсловия CustomAttributes)

        // *** End programmer edit section *** (Условие.НомерУсловия CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string НомерУсловия
        {
            get
            {
                // *** Start programmer edit section *** (Условие.НомерУсловия Get start)

                // *** End programmer edit section *** (Условие.НомерУсловия Get start)
                string result = this.fНомерУсловия;
                // *** Start programmer edit section *** (Условие.НомерУсловия Get end)

                // *** End programmer edit section *** (Условие.НомерУсловия Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Условие.НомерУсловия Set start)

                // *** End programmer edit section *** (Условие.НомерУсловия Set start)
                this.fНомерУсловия = value;
                // *** Start programmer edit section *** (Условие.НомерУсловия Set end)

                // *** End programmer edit section *** (Условие.НомерУсловия Set end)
            }
        }
        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (Условие.Наименование CustomAttributes)

        // *** End programmer edit section *** (Условие.Наименование CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (Условие.Наименование Get start)

                // *** End programmer edit section *** (Условие.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (Условие.Наименование Get end)

                // *** End programmer edit section *** (Условие.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Условие.Наименование Set start)

                // *** End programmer edit section *** (Условие.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (Условие.Наименование Set end)

                // *** End programmer edit section *** (Условие.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Условие.
        /// </summary>
        // *** Start programmer edit section *** (Условие.ВидПоддержки CustomAttributes)

        // *** End programmer edit section *** (Условие.ВидПоддержки CustomAttributes)
        public virtual IIS.ISS5.DetailArrayOfВидПоддержки ВидПоддержки
        {
            get
            {
                // *** Start programmer edit section *** (Условие.ВидПоддержки Get start)

                // *** End programmer edit section *** (Условие.ВидПоддержки Get start)
                if ((this.fВидПоддержки == null))
                {
                    this.fВидПоддержки = new IIS.ISS5.DetailArrayOfВидПоддержки(this);
                }
                IIS.ISS5.DetailArrayOfВидПоддержки result = this.fВидПоддержки;
                // *** Start programmer edit section *** (Условие.ВидПоддержки Get end)

                // *** End programmer edit section *** (Условие.ВидПоддержки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Условие.ВидПоддержки Set start)

                // *** End programmer edit section *** (Условие.ВидПоддержки Set start)
                this.fВидПоддержки = value;
                // *** Start programmer edit section *** (Условие.ВидПоддержки Set end)

                // *** End programmer edit section *** (Условие.ВидПоддержки Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "УсловиеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View УсловиеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("УсловиеE", typeof(IIS.ISS5.Условие));
                }
            }
            
            /// <summary>
            /// "УсловиеL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View УсловиеL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("УсловиеL", typeof(IIS.ISS5.Условие));
                }
            }
        }
    }
}
